import { DataSource } from "typeorm";
import { ProductPlan } from "./src/modules/product-plan/entities/product-plan.entity";
import { PlanList } from "./src/modules/plan-list/entities/plan-list.entity";
import { Priority } from "./src/common/enums/prority.enum";
import { Status } from "./src/common/enums/status.enum";


const AppDataSource = new DataSource({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "root",
    password: "root",
    database: "rmutt_db",
    entities: [ProductPlan, PlanList],
    synchronize: false,
});

async function seed() {
    await AppDataSource.initialize();
    console.log("Connected");

    const planRepo = AppDataSource.getRepository(ProductPlan);
    const listRepo = AppDataSource.getRepository(PlanList);

    const DAYS = 14;
    const PRODUCTS = 20;

    for (let productId = 1; productId <= PRODUCTS; productId++) {
        for (let i = 0; i < DAYS; i++) {
            const date = new Date();
            date.setDate(date.getDate() - (DAYS - i));

            // random quantity realistic
            const qty =
                Math.floor(1800 + Math.random() * 2000); // 1800–3800

            // -------------------------------
            // INSERT product_plan
            // -------------------------------
            const plan = await planRepo.save(
                planRepo.create({
                    product_id: productId,
                    input_quantity: qty,
                    plan_name: `Auto Plan Day ${i + 1}`,
                    plan_description: `Autogenerated seed plan for product ${productId}`,
                    start_date: date,
                    end_date: date,
                })
            );

            // -------------------------------
            // INSERT plan_list (1 row per plan)
            // -------------------------------
            await listRepo.save(
                listRepo.create({
                    plan_id: plan.id,
                    priority: Priority.MEDIUM,
                    status: Status.COMPLETED,
                    updated_at: date,
                })
            );

            console.log(
                `Created Product ${productId} | ${date.toISOString().slice(0, 10)} | Qty ${qty}`
            );
        }
    }

    console.log("✔ DONE SEEDING 14 days");
    process.exit(0);
}

seed();
