export enum NotificationType {
    // Stock & Inventory
    LOW_STOCK = 'LOW_STOCK',
    LOW_STOCK_REMINDER = 'LOW_STOCK_REMINDER',
    MATERIAL_EXPIRING = 'MATERIAL_EXPIRING',
    MATERIAL_EXPIRED = 'MATERIAL_EXPIRED',
    MATERIAL_SHORTAGE = 'MATERIAL_SHORTAGE',
    INVENTORY_RECEIVED = 'INVENTORY_RECEIVED',

    // Production
    PRODUCTION_COMPLETED = 'PRODUCTION_COMPLETED',
    PLAN_STATUS_CHANGED = 'PLAN_STATUS_CHANGED',
    PLAN_DEADLINE_APPROACHING = 'PLAN_DEADLINE_APPROACHING',
    NEW_PLAN_ASSIGNED = 'NEW_PLAN_ASSIGNED',

    // Purchasing
    SUPPLIER_ORDER_REQUIRED = 'SUPPLIER_ORDER_REQUIRED',
}
