export enum AuditAction {
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    RESTORE = 'RESTORE',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    // Plan Workflow Actions
    PLAN_CONFIRMED = 'PLAN_CONFIRMED',
    PLAN_STARTED = 'PLAN_STARTED',
    PLAN_COMPLETED = 'PLAN_COMPLETED',
    PLAN_CANCELLED = 'PLAN_CANCELLED',
    // Stock Operations
    STOCK_RESERVED = 'STOCK_RESERVED',
    STOCK_DEDUCTED = 'STOCK_DEDUCTED',
    STOCK_RETURNED = 'STOCK_RETURNED',
}

